version: '3.9'

services:
  api-jojos-click:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app_network 
    restart: always

networks:
  app_network:
    driver: bridge
